### ISSUE TITLE
Dependency not available. 

### ISSUE THREAD

**Issue by jhirn** [mrsarm/spring-ctx#1]
Hello.

Was trying to use this in conjunction with the jshell plugin and I'm getting depencency not found. Not sure if it was pulled from Maven Central or never published, but I'm interested in a spring boot console so was hoping to give it a spin. 

Thanks!

**Comment by mrsarm** [comment]
Hi @jhirn !

Did you add the Jipack repo to Gradle as mentioned in the [README](https://github.com/mrsarm/spring-ctx#gradle)?:

```groovy
maven { url 'https://jitpack.io' }
```

**Comment by jhirn** [comment]
I promise I read it yet somehow this eluded me, despite searching for if there was a repo to add. 

Thank you!
